[workspace]

members = [
  "crates/configure-holochain",
  "crates/hpos_connect_hc",
  "crates/holo_happ_manager",
  "crates/test_utils"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
