[workspace]
resolver = "2"

members = [
  "crates/configure-holochain",
  "crates/hpos_connect_hc",
  "crates/holo_happ_manager",
  "crates/core_app_cli",
  "crates/holofuel_cli",
  "crates/holofuel_init",
  "crates/taskgroup_manager",
  "crates/holochain_env_setup",
]

[workspace.dependencies]
hpos-config-core = { git = "https://github.com/Holo-Host/hpos-config", rev = "77d740c83a02e322e670e360eb450076b593b328" }
hpos-config-seed-bundle-explorer ={ git = "https://github.com/Holo-Host/hpos-config", rev = "77d740c83a02e322e670e360eb450076b593b328" }
ed25519-dalek = "2.1.1"
holochain_keystore = "0.5.3"
holochain_types = { version = "0.5.3" }
holochain_conductor_api = "0.5.3"
lair_keystore_api = "0.6.2"
holochain_websocket = "0.5.3"
holofuel_types = { git = "https://github.com/holo-host/holofuel", rev = "ef7a5116f0774aa08579182ca1de758d5f38a0e2" }
sodoken = "0.1.0"
serde = { version = "1", features = ["derive", "rc"] } 
rmp-serde = "1.1.1"
mr_bundle = { version = "0.5.3" }
reqwest = { version = "0.12.4", features = ["json"]}
holochain_serialized_bytes = "*"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
