[workspace]

members = [
  "crates/configure-holochain",
  "crates/hpos_connect_hc",
  "crates/holo_happ_manager",
  "crates/core_app_cli",
  "crates/holofuel_cli",
  "crates/holofuel_init",
  "crates/taskgroup_manager",
  "crates/holochain_env_setup",
]

[workspace.dependencies]
hpos-config-core = { git = "https://github.com/Holo-Host/hpos-config", rev = "a36f862869cc162c843ac27ed617910d68f480cc" }
hpos-config-seed-bundle-explorer ={ git = "https://github.com/Holo-Host/hpos-config", rev = "a36f862869cc162c843ac27ed617910d68f480cc" }
ed25519-dalek = "2.1.1"
holochain_client = "=0.5.0-dev.31"
holochain_keystore = "0.3.0-beta-dev.36"
holochain_types = { version = "0.3.0-beta-dev.42", features = ["chc"] }
holochain_conductor_api = "=0.3.0-beta-dev.44"
lair_keystore_api = "=0.4.4"
holochain_websocket = "0.3.0-beta-dev.21"
holofuel_types = "0.5.8"
sodoken = "0.0.11"
serde = "1.0.193" # { version = "1.0.193", features = ["derive"] }
mr_bundle = { version = "0.3.0-beta-dev.10" }
reqwest = { version = "0.12.4", features = ["json"]}

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
