[package]
name = "configure-holochain"
version = "0.3.3"
authors = ["Oleksii Filonenko <oleksii.filonenko@holo.host>", "zo-el <joelulahanna@gmaail.com>"]
edition = "2021"

[dependencies]
again = "0.1"
anyhow = "1.0"
futures = "0.3"
isahc = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.60"
structopt = "0.3"
tempfile = "3.1"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-futures = "0.2"
tracing-subscriber = "0.2"
rmp-serde = "0.14.3"
url = "2.2"
observability = "0.1.3"
base64 = "0.13.0"
reqwest = { version = "0.11", features = ["json"]}
spinning_top = "=0.2.0"
holochain = {version = "0.0.145", default-features = false}
holochain_types = "0.0.43"
holochain_websocket = "0.0.39"
holo_hash = "=0.0.29"
holochain_zome_types = "0.0.37"
hdk_derive = "0.0.27"
failure = "0.1"
lazy_static = "1"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }

[dependencies.hpos-config-core]
git = "https://github.com/Holo-Host/hpos-config"
rev = "62e328974ad738551920c85ced6ddf92f2ece29c"

[dependencies.hpos-config-seed-bundle-explorer]
git = "https://github.com/Holo-Host/hpos-config"
rev = "62e328974ad738551920c85ced6ddf92f2ece29c"

[dev-dependencies.cargo-husky]
version = "1"
features = ["run-cargo-fmt", "run-cargo-clippy"]

[target.'cfg(unix)'.dependencies]
nix = "0.23.0"
