[workspace]

members = [
  "crates/configure-holochain",
  "crates/hpos_connect_hc",
  "crates/holo_happ_manager",
  "crates/test_utils"
]

[workspace.dependencies]
holochain_types = "0.2.2-beta-rc.1"
serde = "1.0"
holochain_conductor_api = "=0.2.2-beta-rc.1"
holochain_keystore = "=0.2.2-beta-rc.1"
holochain_websocket = "0.2.1"
mr_bundle = "0.2.2-beta-rc.0"
lair_keystore_api = "0.3.0"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

