[package]
name = "configure-holochain"
version = "0.5.2"
authors = ["Oleksii Filonenko <oleksii.filonenko@holo.host>", "zo-el <joelulahanna@gmaail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = "0.2"
url = "2.2"
hpos_hc_connect = { version = "0.1.0", path = "../hpos_connect_hc" }


hpos-config-core = { workspace = true }
[dev-dependencies]
test-case = "2.2.2"
serial_test = { version = "0.9.0", features = ["async"] }
test_utils = { path = "../test_utils" }