[package]
name = "configure-holochain"
version = "0.4.0"
authors = ["Oleksii Filonenko <oleksii.filonenko@holo.host>", "zo-el <joelulahanna@gmaail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.11"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = "0.2"
url = "2.2"
# observability = "0.1.3"
holochain_types = "0.2.0"
thiserror = "1.0"
hpos_hc_connect = { path = "../hpos_connect_hc" }

[dependencies.hpos-config-core]
git = "https://github.com/Holo-Host/hpos-config"
rev = "bfaced6044ae570bf20d4528fa9aaafcc43ddeec"

[target.'cfg(unix)'.dependencies]
nix = "0.26.2"

[dev-dependencies]
lair_keystore_api = "0.2.3"
snafu = "0.7.1"
chrono = "0.4.22"
test-case = "2.2.2"
serial_test = { version = "0.9.0", features = ["async"] }
